shashankd14/rubrum-frontend

src/appRedux/sagas/Rates.js, src/routes/company/Master/Rates.js
Code changes for  Multiselect material grade in rates(add, edit)
=> Multiselect material grade in rates(add, edit)

src/routes/company/Master/Party.js
@shashankd14 please validate and approve
=> add party changes for add new record

src/appRedux/sagas/Party.js, src/routes/company/Master/Party.js
@shashankd14  please validate and approve this PR
=> ShowRatesDCFlg Add, edit, view

src/appRedux/sagas/Party.js
=> HotFix in master branch

src/appRedux/sagas/Party.js, src/routes/company/Master/Party.js
@shashankd14 pls validate and approve this pr.
1) commented required field of quality template
2) uncommented code of edit quality template in quality saga.
=> required field commented for quality template

src/routes/company/Partywise/DeliveryInfo.js
@shashankd14 pls validate n approve this pr
1) done changes for full handling validation status
=> full handling validation status issue fixed

src/appRedux/sagas/Quality.js, src/lngProvider/locales/en_US.json, src/routes/company/quality/kqp/Templates.js, src/routes/company/quality/templates/LinkedTemplateList.js, src/routes/company/quality/templates/TemplateList.js, src/routes/company/quality/templates/Templates.js, src/routes/company/quality/templates/create/InwardTemplate.js, src/routes/company/quality/templates/create/PostDispatchTemplate.js, src/routes/company/quality/templates/create/PreProcessingTemplate.js
@shashankd14  please validate and approve this PR
1) Quality template - changed upload image btn name Inward stage
- search functionality 
- change in postDispatch stage
- change in postDispatch stage
2) Linked QT - change in code getAll
3) KQP - Delete functionality
=> Changes in quality template n delete kqp

src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js
@shashankd14 
1) Pagination in QR for all stage
2) Search functionality in QR for all stage
=> Search functionality n pagination issue in QR

src/routes/company/quality/kqp/Templates.js, src/routes/company/quality/kqp/linked/CreateLinkTemplate.js, src/routes/company/quality/reports/ProcessingReport.js, src/routes/company/quality/templates/create/ProcessingTemplate.js, src/routes/company/quality/templates/create/process/CuttingForm.js, src/routes/company/quality/templates/create/process/SlitAndCutForm.js, src/routes/company/quality/templates/create/process/SlittingForm.js, src/routes/company/quality/templates/linked/CreateLinkTemplate.js, yarn.lock
@shashankd14 
1) MatGrade dropdown qt
2) Processwise opening modal in process stage create template
3) save data in api for CuttingForm n Sli&CutForm in process stage create template
4) MatGrade dropdown kqp linked template
=> Processwise opening modal in process stage create template

src/routes/company/Master/Rates.js
@shashankd14 
1) Added material grade column in rate master.
=> added col material grade in rate master

src/routes/company/quality/reports/create/InwardReportTemplate.js, src/routes/company/quality/reports/create/PostDispatchReportTemplate.js, src/routes/company/quality/reports/create/PreDispatchReportTemplate.js, src/routes/company/quality/reports/create/PreProcessingReportTemplate.js, src/routes/company/quality/reports/create/ProcessingReportTemplate.js, src/routes/company/quality/templates/create/PreDispatchTemplate.js
@shashankd14 please verify n approve this PR
1) image button name changes in all stage
2) cancel btn issue resolved
=> img btn name changes

src/routes/company/Master/Rates.js, src/routes/company/Master/addAdditionalRates.js, src/routes/company/Master/editAdditionalRates.js
Issue no. 9
1) added filter in Base rates for columns - party name, process name, material description, grade, thickness range
2) added button for clear filter 
Issue no. 10 
1) added 4 parameters in additional rate  - Add, Edit, View
=> parameters in additional rates, filters in base rate

src/routes/company/Partywise/List.js
@shashankd14 
1) added column - No of Pieces in partywise register
=> added col no of pcs in partywise register

src/appRedux/actions/Rates.js, src/appRedux/reducers/Rates.js, src/appRedux/sagas/Rates.js, src/routes/company/Master/Rates.js
@shashankd14 please validate and approve this PR.
1) pagination in Base Rate
2) search in base rate by party name, process name, mat description, grade, range
=> pagination & search

src/routes/company/Master/Rates.js
@shashankd14 
searchThickness search bar issue
=> search thickness textbox

src/routes/company/Partywise/List.js
@shashankd14 please validate & approve this pr
1) search dropdown issue fixed in partywise register
2) allignment of search dropdown
=> search dropDown record issue in partywiseRegister

src/appRedux/sagas/Quality.js, src/constants/quality/ComponentConstants.js, src/routes/company/Partywise/List.js, src/routes/company/quality/kqp/LinkedTemplateList.js, src/routes/company/quality/kqp/TemplateList.js, src/routes/company/quality/kqp/Templates.js, src/routes/company/quality/kqp/create/CreateTemplate.js, src/routes/company/quality/kqp/linked/CreateLinkTemplate.js, src/routes/company/quality/templates/LinkedTemplateList.js, src/routes/company/quality/templates/TemplateList.js, src/routes/company/quality/templates/Templates.js, src/routes/company/quality/templates/linked/CreateLinkTemplate.js
@shashankd14  Link KQP and Quality Templates related code changes. pls approve.
=> Link KQP and Quality Templates

src/lngProvider/locales/en_US.json, src/routes/company/Inward/List.js, src/routes/company/Master/Material.js, src/routes/company/Master/Packing.js, src/routes/company/Master/Party.js, src/routes/company/Master/Quality.js, src/routes/company/Master/Rates.js, src/routes/company/Master/Tags.js, src/routes/company/Partywise/CuttingModal.js, src/routes/company/Partywise/List.js, src/routes/company/UserAccess/index.js, src/routes/company/quality/kqp/LinkedTemplateList.js, src/routes/company/quality/kqp/TemplateList.js, src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/create/CreateReport.js, src/routes/company/quality/reports/create/InwardReportTemplate.js, src/routes/company/quality/templates/LinkedTemplateList.js, src/routes/company/quality/templates/create/PostDispatchTemplate.js
=> Create Update QR issue fixed, console warnings

src/routes/company/quality/kqp/TemplateList.js, src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/create/CreateReport.js, src/routes/company/quality/reports/create/InwardReportTemplate.js, src/routes/company/quality/reports/create/PostDispatchReportTemplate.js, src/routes/company/quality/reports/create/StatusButton.css, src/routes/company/quality/reports/create/StatusButton.js, src/routes/company/quality/templates/TemplateList.js
@shashankd14 please validate n approve this pr
=> Inward report status, display templateList issue

src/constants/quality/ComponentConstants.js, src/routes/company/quality/kqp/linked/CreateLinkTemplate.js, src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/create/CreateReport.js, src/routes/company/quality/reports/create/PreDispatchReportTemplate.js, src/routes/company/quality/reports/create/PreProcessingReportTemplate.js, src/routes/company/quality/templates/linked/CreateLinkTemplate.js
=> PostDispatch, PreDispatch, anyThickness, PreProcessing

src/routes/company/quality/kqp/linked/CreateLinkTemplate.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js, src/routes/company/quality/reports/create/PreProcessingReportTemplate.js, src/routes/company/quality/templates/create/process/SlittingForm.js, src/routes/company/quality/templates/linked/CreateLinkTemplate.js
@shashankd14 please validate n approve this PR.
=> Select all n any checkbox in QT, KQP and status

src/routes/company/quality/kqp/linked/CreateLinkTemplate.js, src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js, src/routes/company/quality/reports/create/ProcessingReportTemplate.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js, src/routes/company/quality/templates/create/process/CuttingForm.js, src/routes/company/quality/templates/create/process/SlitAndCutForm.js, src/routes/company/quality/templates/linked/CreateLinkTemplate.js
@shashankd14 please validate n approve this PR
1) slitCutForm
2) CutForm
3) tolerance table in Cut n SlitCut in QT n Report 
4) fetched data from QT to Report in tolerance table
=> SliCutFom_CutForm

src/routes/company/Partywise/List.js
=> issue no 23

public/css/style.css, src/routes/company/Partywise/List.js, src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js, src/routes/company/quality/reports/create/CreateReport.js, src/routes/company/quality/reports/create/ProcessingReportTemplate.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js, src/routes/company/quality/templates/create/ProcessingTemplate.js, src/routes/company/quality/templates/create/process/CuttingForm.js, src/routes/company/quality/templates/create/process/SlitAndCutForm.js, src/routes/company/quality/templates/create/process/SlittingForm.js, src/util/EditableTable.js
@shashankd14 pls validate and approve this PR
=> Tolerance table

src/routes/company/quality/kqp/LinkedTemplateList.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js
=> kqpListPage, search, slittingForm, final judgement input

src/routes/company/quality/reports/InwardReport.js
=> compile error

src/appRedux/actions/Quality.js, src/appRedux/reducers/Quality.js, src/appRedux/sagas/Inward.js, src/appRedux/sagas/Quality.js, src/containers/SignIn.js, src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js
=> UI part for QM pdf

src/containers/SignIn.js, src/routes/company/Master/Rates.js, src/routes/company/Master/addAdditionalRates.js, src/routes/company/Partywise/DeliveryInfo.js
@shashankd14 please validate and approve this pr
=> lamination DC issue

src/appRedux/sagas/Quality.js, src/lngProvider/locales/en_US.json, src/routes/company/quality/kqp/Templates.js, src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js, src/routes/company/quality/reports/create/PostDispatchReportTemplate.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js
@shashankd14 please validate and approve this pr
=> tableData issue, postDispatch image save,

src/routes/company/quality/kqp/linked/CreateLinkTemplate.js
=> name issue

src/routes/company/Partywise/CuttingModal.js
=> Display width in Finish Cutting table

src/appRedux/reducers/Quality.js, src/routes/company/quality/kqp/linked/CreateLinkTemplate.js
@shashankd14 please validate and approve this pr
any option in kqp map changes according to api response
=> kqp map any option change according to api change

src/routes/company/quality/kqp/linked/CreateLinkTemplate.js
@shashankd14 please validate n approve this pr
=> kqpMap getById displaying partyName

src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js
@shashankd14 please approve and validate pr
1) added target weight in QR process stage for all processes
2) pdf which is from partywise register linked to document ID for Inward, Pre-processing, Processing
=> targetWeight, planId in table

src/appRedux/sagas/Quality.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js
@shashankd14 please validate n approve this pr
=> preDipatch & postDispatch DC pdf

src/routes/company/quality/kqp/LinkedTemplateList.js
=> KQPlink list according to api response

src/appRedux/sagas/Quality.js, src/routes/company/quality/reports/InwardReport.js
=> Inward QR pdf

src/routes/company/quality/reports/create/ProcessingReportTemplate.js
@shashankd14 pls validate n approve this pr
=> Qr payload and comment

src/routes/company/quality/reports/create/PreDispatchReportTemplate.js
=> commentField in preDispatch

src/routes/company/quality/reports/create/CreateReport.js, src/routes/company/quality/reports/create/InwardReportTemplate.js, src/routes/company/quality/reports/create/PostDispatchReportTemplate.js, src/routes/company/quality/reports/create/PreDispatchReportTemplate.js, src/routes/company/quality/reports/create/PreProcessingReportTemplate.js, src/routes/company/quality/reports/create/ProcessingReportTemplate.js
@shashankd14 pls validate n approve this pr
=> Display comments in View

src/containers/SignIn.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js, src/routes/company/quality/reports/create/CreateReport.js, src/routes/company/quality/reports/create/ProcessingReportTemplate.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js, src/routes/company/quality/templates/create/process/CuttingForm.js, src/routes/company/quality/templates/create/process/SlitAndCutForm.js, src/routes/company/quality/templates/create/process/SlittingForm.js, src/util/EditableTable.js
@shashankd14 pls validate and approve this pr
=> Qr processing view

src/appRedux/sagas/Party.js, src/routes/company/Master/Party.js
@shashankd14 pls validate and approve this pr
=> report checkboxes in partyMaster

src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js, src/routes/company/quality/reports/create/CreateReport.js
@shashankd14 pls validate n approve this PR
=> render issue inQR

src/routes/company/quality/kqp/linked/CreateLinkTemplate.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js, src/routes/company/quality/templates/linked/CreateLinkTemplate.js
=> fieldName changed for pdf issue

src/routes/company/Partywise/CuttingModal.js, src/routes/company/Partywise/SlittingModal.js
@shashankd14 please validate and approve this pr
=> editFinish slitting WIPtoFG, FGtoFG

src/routes/company/quality/reports/create/process/SlitAndCutForm.js
@shashankd14 pls validate n approve this pr
- in QR processsing stage for slitCut process on button click transfer slitting table data to final slitting inspection data.
=> transfer data from slit inspection to final inspection on btn click

src/appRedux/sagas/LabelPrint.js, src/routes/company/Partywise/CuttingModal.js, src/routes/company/Partywise/SlittingModal.js
@shashankd14 
- print label issues - WIPtoFG, FGtoWIP
=> labelPrint issues

src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js
@shashankd14 
1) before generating report display data in cut table
2) report view for all processes
=> cutData populating, view report tableData

src/routes/company/quality/reports/create/ProcessingReportTemplate.js, src/routes/company/quality/reports/create/process/SlittingForm.js
@shashankd14 
1) packing done option on UI in processing stage
2) data transfer button on slit form
=> issue4 and transfer button on slitForm

src/routes/company/quality/reports/create/process/CuttingForm.js
@shashankd14  Fixing compile time errors.
=> Removed unwanted code

src/routes/company/Master/Party.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js, src/util/EditableTableQR.js
@shashankd14 please merge these changes done for "validation according tolerance table for all processes" and added checkbox under monthly report in party master
=> validation according tolerance table for all processes

src/routes/company/Master/Party.js
@shashankd14 
party master update issue in master
=> Party update issue master

src/routes/company/Master/Party.js
@shashankd14 approve this PR
update party master issue
=> update party master issue-UAT

src/appRedux/sagas/Quality.js, src/routes/company/Inward/InwardSteps/InwardEntrySummary.js, src/routes/company/LabelPrint/LabelPrintFG.js, src/routes/company/LabelPrint/LabelPrintInward.js, src/routes/company/LabelPrint/LabelPrintWIP.js, src/routes/company/Partywise/CuttingModal.js, src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js
@shashankd14 
1) search functionality in QR for all stage
2) search functionality in label print for all tab
=> search functionality in QR, label print

src/appRedux/sagas/Quality.js, src/routes/company/Inward/InwardSteps/InwardEntrySummary.js, src/routes/company/LabelPrint/LabelPrintFG.js, src/routes/company/LabelPrint/LabelPrintInward.js, src/routes/company/LabelPrint/LabelPrintWIP.js, src/routes/company/Partywise/CuttingModal.js, src/routes/company/quality/reports/InwardReport.js, src/routes/company/quality/reports/PostDispatchReport.js, src/routes/company/quality/reports/PreDispatchReport.js, src/routes/company/quality/reports/PreProcessingReport.js, src/routes/company/quality/reports/ProcessingReport.js
@shashankd14 
-
1) search functionality in QR all stage
2) search functionality in label print
=> Search functionality qr lp

src/routes/company/quality/kqp/linked/CreateLinkTemplate.js, src/routes/company/quality/templates/linked/CreateLinkTemplate.js
@shashankd14 
1) input text instead of dropdown in KQP link for length, width, thickness.
2) fixed showSearch in thickness QT link.
=> user entered input for length, width, thickness

src/appRedux/sagas/Quality.js, src/routes/company/quality/reports/create/CreateReport.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js, src/util/EditableTableQR.js
@shashankd14 
- validation in QR for 3 processes according to calculation of tolerance data n plan thickness, width, length
- passing payload in process issue
=> validation acording to calculation, create QR

src/appRedux/sagas/Quality.js, src/routes/company/quality/reports/create/CreateReport.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js, src/util/EditableTableQR.js
@shashankd14 
- validation in QR for 3 processes according to calculation of tolerance data n plan thickness, width, length
- passing payload in process issue
=> Validation according to calculation

src/util/EditableTableQR.js
@shashankd14 
-changed validation msg, took range value in validation up to 3 digit no
=> Change validation message

src/routes/company/Partywise/CuttingModal.js
@shashankd14 
[endUserTag - slitCut process for cut passing endUserTagId in request
=> endUserTag issue in slitCut for cut payload

src/routes/company/quality/reports/create/PreDispatchReportTemplate.js, src/routes/company/quality/reports/create/ProcessingReportTemplate.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js
@shashankd14 
1) added quality engineer and quality head in predispatch stage
2) processing stage - replace quality engineer and quality from plan popup to templateDetails
=> add qualityEngineer, qualityHead in preDispatch stage

src/routes/company/Partywise/CuttingModal.js
@shashankd14 
endUserTag issue in slitCut for cut table
=> endUserTag issue in slitCut for cut

src/routes/company/Partywise/CuttingModal.js, src/routes/company/quality/reports/create/PreDispatchReportTemplate.js, src/routes/company/quality/reports/create/ProcessingReportTemplate.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js
@shashankd14 
1) endUsertag issue
2) qualityHead n qualityEngineer in preDispatch stage
=> Quality head quality engineer pre dispatch stage

src/routes/company/Partywise/List.js, src/routes/company/quality/kqp/TemplateList.js, src/routes/company/quality/kqp/linked/CreateLinkTemplate.js
@shashankd14 pls verify and approve merge request
- Any options in KQP Template for Length, Width, Thickness
- Dispatched Coil grid display(issue no 6)
=> anyOption in KQP, issue no. 6

src/routes/company/Partywise/List.js
@shashankd14 
- reverted changes of issue no.6  AFTER COMPLETELY DISPATCHED IT SHOULD HIDE IN DISPLAY
=> changes reverted for issue no.6

src/routes/company/quality/reports/create/process/SlitAndCutForm.js
@shashankd14 
- field name changed for cutting tolerance table
=> cut tolerance field name changed

src/containers/App/index.js
@shashankd14 
refresh token code commented in index component in master
=> refresh token code reverted in master

src/routes/company/Inward/InwardSteps/InvoiceDetailsForm.js
@shashankd14 
- date issue in inward
=> date issue in inward

src/routes/company/Partywise/CuttingModal.js
@shashankd14 
- issue no12 in cut modal balance no of cuts took lowerbound
=> issue no12, cutModal balance is not accepting

src/appRedux/sagas/Inward.js
@shashankd14 
issue no.7 api name change. IN PARTY WISE REGISTER AFTER COMPLETELY DISPATCHED IT SHOULD HIDE IN DISPLAY
=> api name change for issue7

src/routes/company/Partywise/CuttingModal.js
@shashankd14 
orderwise payload sent to cut
=> orderwise payload for cutting

src/routes/company/quality/reports/create/process/SlitAndCutForm.js
@shashankd14 
edit view issue in QR for slitCut process
=> Edit view issue in QR in slitCut process

src/util/EditableTable.js, src/util/EditableTableQR.js
@shashankd14 
- tab moving functionality in QR and QT
=> tab mov functionality in QT, QR

src/appRedux/actions/Inward.js, src/appRedux/sagas/Inward.js, src/containers/SignIn.js, src/routes/company/Partywise/List.js
@shashankd14 
issue no.3 - ascending descending thickness order in partywise register
=> ascending, descending orderwise thickness in partywiseRegister

src/routes/company/Partywise/CuttingModal.js, src/routes/company/Partywise/Plan.js, src/routes/company/Partywise/SlittingModal.js
@shashankd14 
yield loss ratio UI part for slitCut, slit, cut
=> Feature yeildlossratio

src/appRedux/sagas/Quality.js
@shashankd14 
pdf generating issue in QR
=> pdf issue in QR

src/appRedux/sagas/Auth.js
@shashankd14 
refresh token issue
=> refresh token issue

src/containers/App/index.js
@shashankd14 
refresh token api call issue for partywise register
=> token api calling issue for partywise register

src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js, src/routes/company/quality/templates/create/process/CuttingForm.js, src/routes/company/quality/templates/create/process/SlitAndCutForm.js, src/routes/company/quality/templates/create/process/SlittingForm.js
@shashankd14 
replaced name of apen coil to internal coil on slitting, slitCut and Cutting form in QR and QT
=> replaced name of aspen coil to internal coil

src/routes/company/Partywise/CuttingModal.js
=> cut, slitCut ylr in FG

src/containers/App/index.js
=> token with popup

src/routes/company/Partywise/List.js, src/routes/company/Partywise/SlittingModal.js
planned n total yield loss on plan screen
some times blank page showing for partywise register menu
=> Yield loss ratio party

src/routes/company/Partywise/SlittingModal.js, src/routes/company/quality/reports/create/process/CuttingForm.js, src/routes/company/quality/reports/create/process/SlitAndCutForm.js, src/routes/company/quality/reports/create/process/SlittingForm.js
planwise YLR on FG screen for slit
=> plan wise YLR Slit, slitCut on FG screen

src/routes/company/Master/YieldLossRatio.js
=> process tag issue

src/routes/company/Master/YieldLossRatio.js, src/routes/company/Partywise/SlittingModal.js
plan for 2 part issue in slitCut n slit
=> plan for 2 parts issue

src/appRedux/sagas/Inward.js, src/containers/App/index.js, src/routes/company/Partywise/CuttingModal.js, src/routes/company/Partywise/SlittingModal.js
coil level YLR planned n actual on FG screen
=> coil level YLR

src/routes/company/Partywise/SlittingModal.js
in plan screen YLR calculation when there is pagination in table
=> YLR in plan while pagination

src/routes/company/Partywise/CuttingModal.js
after clicking on proceed for cut button blank page was showing
=> slitCut plan issue for YLR

src/routes/company/Partywise/SlittingModal.js
=> coilLevel YLR on plan screen

src/routes/company/Partywise/CuttingModal.js
hard coded date is removed in cut modal
=> hardCoded date removed

src/routes/company/Partywise/SlittingModal.js
=> coilLevel planned weight issue

src/routes/company/Partywise/CuttingModal.js
coil level planned ylr on cut modal
=> coilLevel planned YLR in cutModal

src/appRedux/sagas/Quality.js
=> dcPDF in QR

.github/workflows/test-deploy.yml, package.json
@shashankd14 
changes reverted in package.json
=> packageDot json file revert change

src/appRedux/sagas/Quality.js
@shashankd14 , validate and approve this pr
- QR - pdf generate issue in Pre-Dispatch and post-Dispatch for DC
=> Dc pdf qr 17 5

src/routes/company/Partywise/SlittingModal.js
end user tag issue in slitCut and slit
=> Eut slit cut plan

src/routes/company/Inward/InwardSteps/InwardEntrySummary.js
1. Generate PDF & Label button is enabled whenever inward details were updating
2. Monthly planner tracker report option added in party master
=> Generate PDF & Label button enabled in update inward process

src/routes/company/Partywise/CuttingModal.js
Able to edit the packet classification before edit FG for slit and cut model.
=> able to update the packet classification before FG for slitandcut

src/routes/company/Partywise/CuttingModal.js
null pointer exception handled for tagId field
=> null pointer exception handled for tagId field
